#!/bin/bash

rm formant_data
touch formant_data

for f in `ls recordings/trainingdata`
	do
		#echo $f
		type=`echo $f | grep -o "[A-Za-z]\+[0-9]\+" | grep -o "[A-Za-z]\+"`
		
		echo -n "$type " >> formant_data 
		praat formanter.praat recordings/trainingdata/$f >> formant_data
		
	done


rm formant_data_test
touch formant_data_test
for f in `ls recordings/testdata`
	do
		#echo $f
		type=`echo $f | grep -o "[A-Za-z]\+[0-9]\+" | grep -o "[A-Za-z]\+"`
		
		echo -n "$type " >> formant_data_test
		praat formanter.praat recordings/testdata/$f >> formant_data_test
		
	done
