#!/bin/bash

rm formantdata/formant_data
touch formantdata/formant_data


for d in `ls recordings/trainingdata`
	do
	for f in `ls recordings/trainingdata/$d`
		do
		type=`echo $f | grep -o "[A-Za-z]\+[0-9]\+" | grep -o "[A-Za-z]\+"`
		
		echo -n "$type " >> formantdata/formant_data 
		praat formanter.praat recordings/trainingdata/$d/$f >> formantdata/formant_data
		done
	done


rm formantdata/formant_data_test
touch formantdata/formant_data_test

for d in `ls recordings/testdata`
	do
	for f in `ls recordings/testdata/$d`
		do
		type=`echo $f | grep -o "[A-Za-z]\+[0-9]\+" | grep -o "[A-Za-z]\+"`
		
		echo -n "$type " >> formantdata/formant_data_test
		praat formanter.praat recordings/testdata/$d/$f >> formantdata/formant_data_test
		done
	done

